version: "3"
services:
  newstrapi:
    environment:
      - NODE_ENV=production
    build:
      context: "./newstrapi"
      dockerfile: Dockerfile.prod
    ports:
      - "1337:1337"
    restart: always

  # db:
  #   container_name: progressapp__postgres
  #   image: postgres
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: strapi
  #     POSTGRES_PASSWORD: strapi
  #     POSTGRES_DB: strapi
  #   networks:
  #     - strapi-postgres
  #   restart: always

  next:
    build:
      dockerfile: Dockerfile.prod
      context: "./next"
    ports:
      - "3000:3000"
    restart: always
